### ISSUE TITLE
电击开始生成后起作用的代码是哪一块呀，后端接口代码是哪块呀

### ISSUE THREAD

**Issue by appreciatehxy** [yyym-y/handwriting-digit-identify#1]

**Comment by yyym-y** [comment]
后端开始的代码在 /identify/py/Net.py 中
为了方便使用我把它打包成了一个exe文件并写了一个简单的bat文件(现在看起来很蠢)
代码是大一写的, 可能会有点屎山并且好像还没注释.....轻喷....
如果你需要我训练好的模型可以接着在这个issure上留言, 我上传到网盘给你

**Comment by yyym-y** [comment]
修改了一些因为版本变动导致的BUG以及一些曾经的疏忽
重写了说明文档, 希望能对你有些帮助 (模型还在上传在网盘中,所以README中的下载链接是空的,请稍等)
如果有什么问题可以发issure提问
